version: 0.2
phases: 
  install: 
    runtime-version: 
        java: openjdk8
  pre_build:
    commands:
      - echo nothing to do pre-build phases.......
  build: 
    commands:
      - echo Build started on `date`
      - java -version
      - mvn clean install
      - install the testcases
